steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# Build
- name: 'gcr.io/cloud-builders/npm'
  args: ['build']

# Secret Manager
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args:
  - '-c'
  - |-
    apt install apt-utils && apt install jq
    echo "$$Learn" | jq -r '.Host'
  secretEnv: ['Learn']
availableSecrets:
  secretManager:
  - versionName: projects/215735978261/secrets/learn/versions/latest
    env: 'Learn'