steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# Build
- name: 'gcr.io/cloud-builders/npm'
  args: ['build']

# Secret Manager
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args:
  - '-c'
  - |-
    apt-get update && apt install jq -y
    echo "$$Learn" | jq -r '.CertificateFile'
  secretEnv: ['Learn']
availableSecrets:
  secretManager:
  - versionName: projects/744467107567/secrets/learn/versions/latest
    env: 'Learn'