steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# Build
- name: 'gcr.io/cloud-builders/npm'
  args: ['build']

# Secret Manager
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args:
  - '-c'
  - |-
    curl -L -o /usr/bin/jq.exe https://github.com/stedolan/jq/releases/latest/download/jq-win64.exe
    echo "$$Learn" | jq -r '.Host'
  secretEnv: ['Learn']
availableSecrets:
  secretManager:
  - versionName: projects/215735978261/secrets/learn/versions/latest
    env: 'Learn'